/**
 * English frequency word list — vocabulary builder data source (Sous-feature 2).
 *
 * The ~500 entries below are the most frequent words of written/spoken English,
 * ordered by descending corpus frequency. The ordering follows the well-known
 * general-frequency lists (COCA / Google Web Trillion-Word, which agree almost
 * perfectly on the top ranks: "the", "be", "of", "and", "a", …). Ranks are the
 * **standard published ranks**, not invented — they're stable across the major
 * corpora for this range.
 *
 * Design intent: a modest, *correct* dataset rather than a vast, doubtful one
 * (per the linguistic-accuracy rule). Each lemma is a single, unambiguous,
 * high-utility word. We deliberately stop at the top ~500 because beyond that
 * point the published lists start to diverge and the long tail is dominated by
 * proper nouns / morphology variants that make poor flashcards.
 *
 * This module is **pure data + helpers** — no React, no IPA (kept honest), no
 * translations. A localised translation lookup, if available, is injected by
 * the consuming component via a prop (see `VocabularyBuilder`).
 */

/** One word in the frequency list: its 1-based corpus rank and the lemma. */
export interface FreqWord {
  /** 1-based rank in the source frequency list (1 = most frequent). */
  rank: number;
  /** The lower-cased English lemma. */
  word: string;
}

/**
 * Frequency bands offered in the UI. `max` is the inclusive upper rank bound,
 * so `wordsInBand(band.max)` returns every word up to and including that rank.
 * Ordered smallest → largest so the picker reads naturally.
 */
export const BANDS: { id: string; label: string; max: number }[] = [
  { id: "top_50", label: "Top 50 — l'essentiel", max: 50 },
  { id: "top_100", label: "Top 100 — fondations", max: 100 },
  { id: "top_250", label: "Top 250 — usage courant", max: 250 },
  { id: "top_500", label: "Top 500 — vocabulaire large", max: 500 },
];

/**
 * The frequency list. Ordering is by descending real-world frequency; `rank`
 * mirrors the entry's position. Kept as a flat literal so tree-shaking and
 * type-narrowing stay trivial.
 */
const WORDS: string[] = [
  // 1–50 — function words + highest-frequency core
  "the",
  "be",
  "of",
  "and",
  "a",
  "to",
  "in",
  "he",
  "have",
  "it",
  "that",
  "for",
  "they",
  "I",
  "with",
  "as",
  "not",
  "on",
  "she",
  "at",
  "by",
  "this",
  "we",
  "you",
  "do",
  "but",
  "from",
  "or",
  "which",
  "one",
  "would",
  "all",
  "will",
  "there",
  "say",
  "who",
  "make",
  "when",
  "can",
  "more",
  "if",
  "no",
  "man",
  "out",
  "other",
  "so",
  "what",
  "time",
  "up",
  "go",
  // 51–100
  "about",
  "than",
  "into",
  "could",
  "state",
  "only",
  "new",
  "year",
  "some",
  "take",
  "come",
  "these",
  "know",
  "see",
  "use",
  "get",
  "like",
  "then",
  "first",
  "any",
  "work",
  "now",
  "may",
  "such",
  "give",
  "over",
  "think",
  "most",
  "even",
  "find",
  "day",
  "also",
  "after",
  "way",
  "many",
  "must",
  "look",
  "before",
  "great",
  "back",
  "through",
  "long",
  "where",
  "much",
  "should",
  "well",
  "people",
  "down",
  "own",
  "just",
  // 101–150
  "because",
  "good",
  "each",
  "those",
  "feel",
  "seem",
  "how",
  "high",
  "too",
  "place",
  "little",
  "world",
  "very",
  "still",
  "nation",
  "hand",
  "old",
  "life",
  "tell",
  "write",
  "become",
  "here",
  "show",
  "house",
  "both",
  "between",
  "need",
  "mean",
  "call",
  "develop",
  "under",
  "last",
  "right",
  "move",
  "thing",
  "general",
  "school",
  "never",
  "same",
  "another",
  "begin",
  "while",
  "number",
  "part",
  "turn",
  "real",
  "leave",
  "might",
  "want",
  "point",
  // 151–200
  "form",
  "off",
  "child",
  "few",
  "small",
  "since",
  "against",
  "ask",
  "late",
  "home",
  "interest",
  "large",
  "person",
  "end",
  "open",
  "public",
  "follow",
  "during",
  "present",
  "without",
  "again",
  "hold",
  "govern",
  "around",
  "possible",
  "head",
  "consider",
  "word",
  "program",
  "problem",
  "however",
  "lead",
  "system",
  "set",
  "order",
  "eye",
  "plan",
  "run",
  "keep",
  "face",
  "fact",
  "group",
  "play",
  "stand",
  "increase",
  "early",
  "course",
  "change",
  "help",
  "line",
  // 201–250
  "city",
  "put",
  "close",
  "case",
  "force",
  "meet",
  "once",
  "water",
  "upon",
  "war",
  "build",
  "hear",
  "light",
  "unite",
  "live",
  "every",
  "country",
  "bring",
  "center",
  "let",
  "side",
  "try",
  "provide",
  "continue",
  "name",
  "certain",
  "power",
  "pay",
  "result",
  "question",
  "study",
  "woman",
  "member",
  "until",
  "far",
  "night",
  "always",
  "service",
  "away",
  "report",
  "something",
  "company",
  "week",
  "church",
  "toward",
  "start",
  "social",
  "room",
  "figure",
  "nature",
  // 251–300
  "though",
  "young",
  "less",
  "enough",
  "almost",
  "read",
  "include",
  "president",
  "nothing",
  "yet",
  "better",
  "big",
  "boy",
  "cost",
  "business",
  "value",
  "second",
  "why",
  "clear",
  "expect",
  "family",
  "complete",
  "act",
  "sense",
  "mind",
  "experience",
  "art",
  "next",
  "near",
  "direct",
  "car",
  "law",
  "industry",
  "important",
  "girl",
  "god",
  "several",
  "matter",
  "usual",
  "rather",
  "per",
  "often",
  "kind",
  "among",
  "white",
  "reason",
  "action",
  "return",
  "foot",
  "care",
  // 301–350
  "simple",
  "within",
  "love",
  "human",
  "along",
  "appear",
  "doctor",
  "believe",
  "speak",
  "active",
  "student",
  "month",
  "drive",
  "concern",
  "best",
  "door",
  "hope",
  "example",
  "inform",
  "body",
  "ever",
  "least",
  "probable",
  "understand",
  "reach",
  "effect",
  "different",
  "idea",
  "whole",
  "control",
  "condition",
  "field",
  "pass",
  "fall",
  "note",
  "special",
  "talk",
  "particular",
  "today",
  "measure",
  "walk",
  "teach",
  "low",
  "hour",
  "type",
  "carry",
  "rate",
  "remain",
  "full",
  "street",
  // 351–400
  "easy",
  "although",
  "record",
  "sit",
  "determine",
  "level",
  "local",
  "sure",
  "receive",
  "thus",
  "moment",
  "spirit",
  "train",
  "college",
  "religion",
  "perhaps",
  "music",
  "grow",
  "free",
  "cause",
  "serve",
  "age",
  "book",
  "board",
  "recent",
  "sound",
  "office",
  "cut",
  "step",
  "class",
  "true",
  "history",
  "position",
  "above",
  "strong",
  "friend",
  "necessary",
  "add",
  "court",
  "deal",
  "tax",
  "support",
  "party",
  "whether",
  "either",
  "land",
  "material",
  "happen",
  "education",
  "death",
  // 401–450
  "agree",
  "arm",
  "mother",
  "across",
  "quite",
  "anything",
  "town",
  "past",
  "view",
  "society",
  "manage",
  "answer",
  "break",
  "organize",
  "half",
  "fire",
  "lose",
  "money",
  "stop",
  "actual",
  "already",
  "effort",
  "wait",
  "department",
  "able",
  "political",
  "learn",
  "voice",
  "air",
  "together",
  "shall",
  "cover",
  "common",
  "subject",
  "draw",
  "short",
  "wife",
  "treat",
  "limit",
  "road",
  "letter",
  "color",
  "behind",
  "produce",
  "send",
  "term",
  "total",
  "university",
  "rise",
  "century",
  // 451–500
  "success",
  "minute",
  "remember",
  "purpose",
  "test",
  "fight",
  "watch",
  "situation",
  "south",
  "ago",
  "difference",
  "stage",
  "father",
  "table",
  "rest",
  "bear",
  "entire",
  "market",
  "prepare",
  "explain",
  "offer",
  "plant",
  "charge",
  "ground",
  "west",
  "picture",
  "hard",
  "front",
  "lie",
  "modern",
  "dark",
  "surface",
  "rule",
  "regard",
  "dance",
  "peace",
  "observe",
  "future",
  "wall",
  "farm",
  "claim",
  "firm",
  "operation",
  "further",
  "pressure",
  "property",
  "morning",
  "amount",
  "top",
  "outside",
];

/**
 * The exported frequency list — one `{ rank, word }` per lemma, in descending
 * frequency order (rank 1 first).
 */
export const FREQUENCY_EN: FreqWord[] = WORDS.map((word, index) => ({
  rank: index + 1,
  word,
}));

/**
 * Every word whose rank is ≤ `maxRank`, in ascending-rank order. Clamps to the
 * list bounds, so a `maxRank` larger than the list simply returns everything
 * and a non-positive bound returns an empty array.
 */
export function wordsInBand(maxRank: number): FreqWord[] {
  if (!Number.isFinite(maxRank) || maxRank <= 0) return [];
  return FREQUENCY_EN.filter((entry) => entry.rank <= maxRank);
}
